---
description: >
  The Diagnostic Assessment and Achievement of College Skills (DAACS) is a suite of technological and social
  supportes to optimize student learning. DAACS provides personalized feedback about students' strengths
  and weaknesses in terms of key academic and self-regulated learning skills, linking them to resources
  to help them be successful students.
images:
  - "socialmedia2.png"

geekdocToC: 3
geekdocTagsToMenu: true

geekdocRepo: https://github.com/daacs/documentation
geekdocEditPath: edit/master

geekdocSearch: true
geekdocSearchShowParent: true

# geekdocLegalNotice: https://thegeeklab.de/legal-notice/#contact-information
# geekdocPrivacyPolicy: https://thegeeklab.de/legal-notice/#privacy-policy

# (Optional, default static/brand.svg) Set the path to a logo for the Geekdoc
# relative to your 'static/' folder.
geekdocLogo: DAACS_logo_inverse.png

# (Optional, default true) Enables search function with flexsearch.
# Index is built on the fly and might slow down your website.
geekdocSearch: true

# (Optional, default true) Display a "Back to top" link in the site footer.
geekdocBackToTop: false


# (Optional, default false) Display search results with the parent folder as prefix. This
# option allows you to distinguish between files with the same name in different folders.
# NOTE: This parameter only applies when 'geekdocSearch: true'.
geekdocSearchShowParent: true

geekdocImageLazyLoading: true
geekdocDarkModeDim: true


