language: r
cache: packages

env:
  global:
    secure: dT0qVZ0gGLkhO7Zy76q+xqqMcnOB6A/sL7zMvxs9u6llorCkPEbbY59lwsKMNVMM2e3bO1XJ1OLt5YdFER+TxBqZi2fNEEZrgWRKFt/F0gFf07dRUVlLdNj+ybl+VjrHxlphYPMAVmwM8yUkHqI85gtsVLP3sZteWePWNXUl7Os2saYkC1/9Mf1/TUrxRycg4LeHfjONAE7VTW3elCw07p5FQroX2j10ZawX6iwfawa2lw4Nf7prGcL9tG+y+tLqE+HAI5x/D6rDoCaqEfFQSPP9+JAU6XYLnUzzBtuGi5ot11kKfo9NIfhwOr3/nVovakvGYQ9aJ02AEfVdOCKJ1dUL9ZYoat+pw9Yl/2pQLCwFSwu2QSdcLrKiDi0Iow5nrmWgeCly83QxcndBD5Ktelly6SPm1imp379605w0Y3TuTX1h2JVVAUEjJnKzs5JqCWS5D5HKRAtA6CQ6uC0iGiDJXbLm+PxAO/udz1AFiofwGIDPrSg7AFZnwfwfTtj93+iktIi8xSIK92zU5GP+JHUpBcSIRtrMeNBjQ8IoB6pJY95/PALdUng7wnBstHjR/qffGyQFaSAWjMfecFtI1AMuIxPQYgvU9YuURTf1TRZpcLqvA/21vFzX7JR7Y3yDLnjOtCFGTMmBYx0/DC/ckfDDsEDTIY7acTpqxeuTZgI=

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
